### ISSUE TITLE
inventory of WQP taking a long time

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-validation#1]
In test run, `whatWQPdata` takes ~1-2 minutes for 4 sites and 1 variable. This seems too long -- maybe have to query by larger spatial extent (e.g., HUCs) and then subset?

**Comment by jordansread** [comment]
Am reviewing now, but I think that it is much faster to use `whatWQP` data across a large number (even national?) of sites that it is to call it per site. I think I can provide a suggestion in the PR.

**Comment by jordansread** [comment]
I get 603994 sites by removing the site id filter and using "Temperature"               "Temperature, sample"       "Temperature, water"        "Temperature, water, deg F" for `whatWQPdata`
That query takes close to 10 mins. 
Using 4 sites is shorter. But how long does it take for 1000 sites? 

update, 1000 sites takes the same(!) amount as 4 sites. So I think that is our winner.

**Comment by limnoliver** [comment]
Crazy! Glad to hear this method will work.
